### PR TITLE
Support Filament v3

### LINKED ISSUE #22: Filament v3 support
## Describe the ideal solution or feature request
Filament 3 was released and the current filament-maps plugin is not compatible. 

> Problem 1
>     - Root composer.json requires filament/filament ^3.0-stable, found filament/filament[v3.0.0, ..., 3.x-dev] but these were not loaded, likely because it conflicts with another require.
>   Problem 2
>     - webbingbrasil/filament-maps is locked to version v1.4.3 and an update of this package was not requested.
>     - webbingbrasil/filament-maps v1.4.3 requires filament/filament ^2.16 -> found filament/filament[v2.16.0, ..., 2.x-dev] but it conflicts with your root composer.json require (^3.0-stable).

### PR DESCRIPTION
**Pull request by d8vjork**
Thanks to the fork @michaelklopf (my fork is based from his)

I did a couple of modifications thought so it fully works with Filament v3, maybe with more testing needed as I'm using only a small part of this on my project but it works

Fixes #22

### CODE REVIEW

**Comment by markparolisi** [comment]
I tried this but got an error for the missing interface, `RendersFormComponentActionModal`

**Comment by invaders-xx** [comment]
@dmandrade, any chance to get this request merged ?

**Comment by danharper83** [comment]
I'm also looking at using this, any update on 3.x version?

**Comment by d8vjork** [comment]
@markparolisi sorry for the late, how did you get into that error?

**Comment by dmandrade** [comment]
I merged this PR to make an initial version available.

However, I am working in parallel on a version with more adjustments and improvements to be released this month.

**Comment by d8vjork** [comment]
@dmandrade Wonderful, glad you took over this

**Comment by dmandrade** [comment]
Version [v3.0.0-beta.1](https://packagist.org/packages/webbingbrasil/filament-maps#v3.0.0-beta.1) have support to Filament v3
I tested all functions and drawing features but there will probably still be more scenarios to be validated.

**Pull request merged**
